<?php
declare(strict_types=1);

require_once __DIR__ . '/includes/config.php';

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

if (!isset($conn) || !($conn instanceof mysqli)) {
    die('Database connection not found.');
}

$conn->set_charset('utf8mb4');

if (!function_exists('h')) {
    function h($value): string
    {
        return htmlspecialchars((string)($value ?? ''), ENT_QUOTES, 'UTF-8');
    }
}


$referral_old = is_array($_SESSION['referral_old'] ?? null)
    ? $_SESSION['referral_old']
    : [];

if (!function_exists('referral_old')) {
    function referral_old(string $key, string $default = ''): string
    {
        global $referral_old;

        return isset($referral_old[$key])
            ? (string)$referral_old[$key]
            : $default;
    }
}

$errors = is_array($_SESSION['referral_errors'] ?? null)
    ? $_SESSION['referral_errors']
    : [];

$success = trim((string)($_SESSION['referral_success'] ?? ''));

/*
 * Flash messages are consumed by this page.
 * Old form values are copied above and can therefore also be cleared.
 */
unset(
    $_SESSION['referral_errors'],
    $_SESSION['referral_success'],
    $_SESSION['referral_old']
);

/*
 * CSRF token is generated by the frontend and verified by
 * includes/process-referral.php.
 */
if (
    empty($_SESSION['referral_csrf']) ||
    !is_string($_SESSION['referral_csrf'])
) {
    $_SESSION['referral_csrf'] = bin2hex(random_bytes(32));
}

$site_name = function_exists('get_setting')
    ? get_setting($conn, 'site_name', 'Mastercard Foundation EdTech Fellowship')
    : 'Mastercard Foundation EdTech Fellowship';

$page_title = 'Cohort 2 Venture Referral Form - ' . $site_name;

include __DIR__ . '/includes/header.php';
?>

<main class="referral-page">

    <section class="referral-hero">
        <div class="container">
            <div class="referral-hero__inner">

                <div class="referral-hero__badge">
                    <i class="fas fa-handshake"></i>
                    Cohort 2 Venture Referral
                </div>

                <h1>Refer a promising EdTech venture</h1>

                <p class="referral-hero__lead">
                    Do you know an innovative EdTech venture working to improve access
                    to quality education with the potential to grow and scale?
                </p>

                <p class="referral-hero__text">
                    Hive Colab invites ecosystem partners, investors, mentors, institutions
                    and other stakeholders to refer promising ventures for consideration
                    for the Mastercard Foundation EdTech Fellowship - Uganda, Cohort 2. </p>
                    <p class="referral-hero__text"> Qualified ventures can self-refer by completing the form, clearly providing all required information to support the referral and subsequent assessment. 
                </p>

            </div>
        </div>
    </section>


    <section class="referral-section">
        <div class="container">

            <div class="referral-layout">

                <aside class="referral-sidebar">

                    <div class="referral-info-card">
                        <div class="referral-info-card__icon">
                            <i class="fas fa-info-circle"></i>
                        </div>

                        <h2>Before you refer</h2>

                        <p>
                            A referral does not constitute acceptance into the Fellowship.
                            Referred ventures will be contacted and invited to submit an
                            application, subject to meeting the programme's eligibility requirements.
                        </p>
                    </div>

                    <div class="referral-steps">
                        <div class="referral-step">
                            <span>1</span>
                            <div>
                                <strong>Your Details</strong>
                                <small>Tell us who is making the referral.</small>
                            </div>
                        </div>

                        <div class="referral-step">
                            <span>2</span>
                            <div>
                                <strong>Venture Details</strong>
                                <small>Share information about the venture.</small>
                            </div>
                        </div>

                        <div class="referral-step">
                            <span>3</span>
                            <div>
                                <strong>Confirmation</strong>
                                <small>Confirm consent and accuracy.</small>
                            </div>
                        </div>
                    </div>

                </aside>


                <div class="referral-form-card">

                    <div class="referral-form-card__header">
                        <div>
                            <span class="referral-form-card__eyebrow">
                                Mastercard Foundation EdTech Fellowship - Uganda
                            </span>
                            <h2>Cohort 2 Venture Referral Form</h2>
                            <p>
                                Complete all required fields below. Fields marked
                                <span class="referral-required">*</span> are mandatory.
                            </p>
                        </div>
                    </div>


                    <?php if ($success !== ''): ?>
                        <div class="referral-alert referral-alert--success" role="status" aria-live="polite">
                            <i class="fas fa-check-circle"></i>
                            <div>
                                <strong>Referral submitted</strong>
                                <span><?= h($success) ?></span>
                            </div>
                        </div>
                    <?php endif; ?>


                    <?php if ($errors): ?>
                        <div class="referral-alert referral-alert--error" role="alert" aria-live="assertive">
                            <i class="fas fa-exclamation-circle"></i>
                            <div>
                                <strong>Please check the form</strong>
                                <ul>
                                    <?php foreach ($errors as $error): ?>
                                        <li><?= h($error) ?></li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                        </div>
                    <?php endif; ?>


                    <form method="POST" action="includes/process-referral.php" class="referral-form" id="referralForm" novalidate>
                        <input
                            type="hidden"
                            name="csrf_token"
                            value="<?= h((string)$_SESSION['referral_csrf']) ?>"
                        >


                        <!-- SECTION 1 -->
                        <fieldset class="referral-fieldset">
                            <legend>
                                <span class="referral-section-number">1</span>
                                <span>
                                    <strong>Your Details</strong>
                                    <small>Information about the person making the referral.</small>
                                </span>
                            </legend>

                            <div class="referral-grid referral-grid--2">

                                <div class="referral-field">
                                    <label for="full_name">
                                        Full Name <span class="referral-required">*</span>
                                    </label>

                                    <input
                                        type="text"
                                        id="full_name"
                                        name="full_name"
                                        value="<?= h(referral_old('full_name')) ?>"
                                        autocomplete="name"
                                        placeholder="e.g. Sarah Namusoke"
                                        aria-describedby="full_name_hint"
                                        required
                                    >
                                    <small class="referral-help referral-field-hint" id="full_name_hint">
                                        Enter your full name as you would like it recorded on the referral.
                                    </small>
                                </div>

                                <div class="referral-field">
                                    <label for="organisation">
                                        Organisation <span class="referral-required">*</span>
                                    </label>

                                    <input
                                        type="text"
                                        id="organisation"
                                        name="organisation"
                                        value="<?= h(referral_old('organisation')) ?>"
                                        autocomplete="organization"
                                        placeholder="e.g. Hive Colab"
                                        aria-describedby="organisation_hint"
                                        required
                                    >
                                    <small class="referral-help referral-field-hint" id="organisation_hint">
                                        Enter the organisation, institution, company, or network you represent.
                                    </small>
                                </div>

                                <div class="referral-field">
                                    <label for="role_position">
                                        Role / Position <span class="referral-required">*</span>
                                    </label>

                                    <input
                                        type="text"
                                        id="role_position"
                                        name="role_position"
                                        value="<?= h(referral_old('role_position')) ?>"
                                        autocomplete="organization-title"
                                        placeholder="e.g. Programme Manager"
                                        aria-describedby="role_position_hint"
                                        required
                                    >
                                    <small class="referral-help referral-field-hint" id="role_position_hint">
                                        Enter your current role or position in the organisation.
                                    </small>
                                </div>

                                <div class="referral-field">
                                    <label for="email">
                                        Email Address <span class="referral-required">*</span>
                                    </label>

                                    <input
                                        type="email"
                                        id="email"
                                        name="email"
                                        value="<?= h(referral_old('email')) ?>"
                                        autocomplete="email"
                                        placeholder="e.g. sarah@example.com"
                                        aria-describedby="email_hint"
                                        required
                                    >
                                    <small class="referral-help referral-field-hint" id="email_hint">
                                        Use an active email address where the programme team can reach you.
                                    </small>
                                </div>

                                <div class="referral-field">
                                    <label for="telephone">
                                        Telephone Number <span class="referral-required">*</span>
                                    </label>

                                    <input
                                        type="tel"
                                        id="telephone"
                                        name="telephone"
                                        value="<?= h(referral_old('telephone')) ?>"
                                        autocomplete="tel"
                                        placeholder="e.g. +256 700 123 456"
                                        aria-describedby="telephone_hint"
                                        required
                                    >
                                    <small class="referral-help referral-field-hint" id="telephone_hint">
                                        Include the country code, for example +256 for Uganda.
                                    </small>
                                </div>

                                <div class="referral-field referral-field--full">
                                    <label for="relationship_to_venture">
                                        How do you know this venture?
                                        <span class="referral-required">*</span>
                                    </label>

                                    <textarea
                                        id="relationship_to_venture"
                                        name="relationship_to_venture"
                                        rows="4"
                                        placeholder="e.g. I have mentored the founders for the past year and have followed the venture's work with schools."
                                        aria-describedby="relationship_to_venture_hint"
                                        required
                                    ><?= h(referral_old('relationship_to_venture')) ?></textarea>
                                    <small class="referral-help referral-field-hint" id="relationship_to_venture_hint">
                                        Briefly describe your relationship to the venture, founder, or team and how long you have known them.
                                    </small>
                                </div>

                            </div>
                        </fieldset>


                        <!-- SECTION 2 -->
                        <fieldset class="referral-fieldset">
                            <legend>
                                <span class="referral-section-number">2</span>
                                <span>
                                    <strong>Venture Details</strong>
                                    <small>Tell us about the venture you are recommending.</small>
                                </span>
                            </legend>

                            <div class="referral-grid referral-grid--2">

                                <div class="referral-field">
                                    <label for="venture_name">
                                        Venture Name <span class="referral-required">*</span>
                                    </label>

                                    <input
                                        type="text"
                                        id="venture_name"
                                        name="venture_name"
                                        value="<?= h(referral_old('venture_name')) ?>"
                                        placeholder="e.g. EduConnect Uganda"
                                        aria-describedby="venture_name_hint"
                                        required
                                    >
                                    <small class="referral-help referral-field-hint" id="venture_name_hint">
                                        Enter the venture's official or commonly used name.
                                    </small>
                                </div>

                                <div class="referral-field">
                                    <label for="founder_name">
                                        Founder / Primary Contact Name
                                        <span class="referral-required">*</span>
                                    </label>

                                    <input
                                        type="text"
                                        id="founder_name"
                                        name="founder_name"
                                        value="<?= h(referral_old('founder_name')) ?>"
                                        placeholder="e.g. John Okello"
                                        aria-describedby="founder_name_hint"
                                        required
                                    >
                                    <small class="referral-help referral-field-hint" id="founder_name_hint">
                                        Enter the founder or primary contact person's full name.
                                    </small>
                                </div>

                                <div class="referral-field">
                                    <label for="founder_email">
                                        Founder / Primary Contact Email
                                        <span class="referral-required">*</span>
                                    </label>

                                    <input
                                        type="email"
                                        id="founder_email"
                                        name="founder_email"
                                        value="<?= h(referral_old('founder_email')) ?>"
                                        placeholder="e.g. founder@educonnect.ug"
                                        aria-describedby="founder_email_hint"
                                        required
                                    >
                                    <small class="referral-help referral-field-hint" id="founder_email_hint">
                                        Provide an active email address where the founder or primary contact can be reached.
                                    </small>
                                </div>

                                <div class="referral-field">
                                    <label for="website_link">
                                        Website or Product Link
                                        <span class="referral-optional">Optional</span>
                                    </label>

                                    <input
                                        type="url"
                                        id="website_link"
                                        name="website_link"
                                        value="<?= h(referral_old('website_link')) ?>"
                                        placeholder="e.g. https://www.educonnect.ug"
                                        aria-describedby="website_link_hint"
                                    >
                                    <small class="referral-help referral-field-hint" id="website_link_hint">
                                        Add the venture website, product page, app link, or another relevant public link if available.
                                    </small>
                                </div>

                                <div class="referral-field referral-field--full">
                                    <div class="referral-label-row">
                                        <label for="referral_reason">
                                            Briefly tell us why you are referring this venture.
                                            <span class="referral-required">*</span>
                                        </label>

                                        <span class="referral-word-count" id="referralWordCount">
                                            0 / 150 words
                                        </span>
                                    </div>

                                    <textarea
                                        id="referral_reason"
                                        name="referral_reason"
                                        rows="6"
                                        maxlength="1800"
                                        data-max-words="150"
                                        placeholder="Briefly explain the venture's innovation, impact, traction, team strength, growth potential, or why it is a strong fit for the Fellowship."
                                        aria-describedby="referral_reason_hint"
                                        required
                                    ><?= h(referral_old('referral_reason')) ?></textarea>

                                    <small class="referral-help referral-field-hint" id="referral_reason_hint">
                                        Highlight the venture's innovation, education impact, traction, team, growth potential, or other qualities that make it suitable. Maximum 150 words.
                                    </small>
                                </div>

                            </div>
                        </fieldset>


                        <!-- SECTION 3 -->
                        <fieldset class="referral-fieldset referral-fieldset--confirmation">
                            <legend>
                                <span class="referral-section-number">3</span>
                                <span>
                                    <strong>Confirmation</strong>
                                    <small>Please confirm the statements below.</small>
                                </span>
                            </legend>

                            <div class="referral-confirm-block">

                                <p class="referral-confirm-question">
                                    Has the venture been informed that you are referring them to
                                    the Mastercard Foundation EdTech Fellowship?
                                    <span class="referral-required">*</span>
                                </p>

                                <div class="referral-choice-grid">

                                    <label class="referral-choice">
                                        <input
                                            type="radio"
                                            name="venture_informed"
                                            value="yes"
                                            <?= referral_old('venture_informed') === 'yes' ? 'checked' : '' ?>
                                            required
                                        >
                                        <span class="referral-choice__box">
                                            <i class="fas fa-check"></i>
                                        </span>
                                        <span>Yes</span>
                                    </label>

                                    <label class="referral-choice">
                                        <input
                                            type="radio"
                                            name="venture_informed"
                                            value="no"
                                            <?= referral_old('venture_informed') === 'no' ? 'checked' : '' ?>
                                            required
                                        >
                                        <span class="referral-choice__box">
                                            <i class="fas fa-times"></i>
                                        </span>
                                        <span>No</span>
                                    </label>

                                </div>
                            </div>


                            <label class="referral-consent">
                                <input
                                    type="checkbox"
                                    name="information_accurate"
                                    value="1"
                                    <?= referral_old('information_accurate') === '1' ? 'checked' : '' ?>
                                    required
                                >

                                <span class="referral-consent__box">
                                    <i class="fas fa-check"></i>
                                </span>

                                <span>
                                    I confirm that the information provided is accurate to the best
                                    of my knowledge.
                                    <span class="referral-required">*</span>
                                </span>
                            </label>

                        </fieldset>


                        <div class="referral-form-footer">
                            <div class="referral-form-note">
                                <i class="fas fa-lock"></i>
                                Your information will be used only for programme referral and follow-up purposes.
                            </div>

                            <button type="submit" class="btn btn-primary referral-submit-btn" id="referralSubmitBtn">
                                <i class="fas fa-paper-plane"></i>
                                <span>Submit Venture Referral</span>
                            </button>
                        </div>

                    </form>

                </div>

            </div>
        </div>
    </section>

</main>



<style>

/* ==========================================================
   FORM PLACEHOLDERS AND FIELD HINTS
========================================================== */
.referral-field input::placeholder,
.referral-field textarea::placeholder {
    color: #8a94a3;
    opacity: 1;
}

.referral-field-hint {
    display: block;
    margin-top: 7px;
    color: #687386;
    font-size: 12px;
    line-height: 1.45;
}

.referral-field input:focus + .referral-field-hint,
.referral-field textarea:focus + .referral-field-hint {
    color: #475569;
}

/* ==========================================================
   REFERRAL FLASH MESSAGE - 5 SECOND AUTO FADE
========================================================== */
.referral-alert {
    opacity: 1;
    visibility: visible;
    max-height: 500px;
    overflow: hidden;
    transition:
        opacity .6s ease,
        transform .6s ease,
        max-height .6s ease,
        margin .6s ease,
        padding .6s ease,
        visibility .6s ease;
}

.referral-alert.is-fading {
    opacity: 0;
    visibility: hidden;
    transform: translateY(-8px);
    max-height: 0;
    margin-top: 0 !important;
    margin-bottom: 0 !important;
    padding-top: 0 !important;
    padding-bottom: 0 !important;
}

.referral-alert.is-removed {
    display: none !important;
}

@media (prefers-reduced-motion: reduce) {
    .referral-alert {
        transition: none;
    }
}
</style>

<script>
(function () {
    const form = document.getElementById('referralForm');
    const reason = document.getElementById('referral_reason');
    const counter = document.getElementById('referralWordCount');
    const submitBtn = document.getElementById('referralSubmitBtn');

    function countWords(value) {
        const clean = String(value || '').trim();

        if (!clean) {
            return 0;
        }

        return clean.split(/\s+/).filter(Boolean).length;
    }

    function updateWordCount() {
        if (!reason || !counter) {
            return;
        }

        const words = countWords(reason.value);
        counter.textContent = `${words} / 150 words`;
        counter.classList.toggle('is-over', words > 150);
    }

    reason?.addEventListener('input', updateWordCount);
    updateWordCount();

    form?.addEventListener('submit', function (event) {
        const words = countWords(reason?.value || '');

        if (words > 150) {
            event.preventDefault();
            reason?.focus();
            updateWordCount();
            return;
        }

        if (!form.checkValidity()) {
            event.preventDefault();
            form.reportValidity();
            return;
        }

        if (submitBtn) {
            submitBtn.disabled = true;
            submitBtn.classList.add('is-loading');
            submitBtn.innerHTML =
                '<i class="fas fa-spinner fa-spin"></i><span>Submitting...</span>';
        }
    });

    /* ==========================================================
       AUTO-HIDE SUCCESS / ERROR FLASH MESSAGES
       Keep visible for 5 seconds, then fade and remove.
    ========================================================== */
    const flashAlerts = document.querySelectorAll('.referral-alert');

    flashAlerts.forEach(function (alert) {
        window.setTimeout(function () {
            alert.classList.add('is-fading');

            window.setTimeout(function () {
                alert.classList.add('is-removed');
                alert.setAttribute('aria-hidden', 'true');
            }, 650);
        }, 5000);
    });

})();
</script>

<?php include __DIR__ . '/includes/footer.php'; ?>
